name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '00 12 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "TRUE"
          SHOW_PROJECTS: "TRUE"
          COMMIT_BY_ME: "TRUE"
          COMMIT_USERNAME: "TRUE"
          COMMIT_MESSAGE: "TRUE"
          SHOW_TOTAL_CODE_TIME: "TRUE"
          COMMIT_EMAIL: "TRUE"
          SHOW_UPDATED_DATE: "TRUE"
          SHOW_LINES_OF_CODE: "TRUE"
          SHOW_PROFILE_VIEWS: "TRUE"
          SHOW_COMMIT: "TRUE"
          SHOW_LANGUAGE: "TRUE"
          SHOW_DAYS_OF_WEEK: "TRUE"
          SHOW_TIMEZONE: "TRUE"
          SHOW_EDITORS: "TRUE"
          SHOW_LANGUAGE_PER_REPO: "TRUE"
          SHOW_SHORT_INFO: "TRUE" 
          SHOW_LOC_CHART: "TRUE"
          SHOW_DAYS_OF_WEEK": "TRUE" 
          

